### ISSUE TITLE
Episode info

### ISSUE THREAD

**Issue by mzp** [mzp/fumifumi#64]
* [x] show metadata at episode page(#65)
 * [x] show magazine name at episode page
 * [x] create author page at JSX (#70)
 * [x] link to author page (#70)
 * [x] create magazine page (#75)
 * [x] link to magazine page (#75)
